### ISSUE TITLE
Host/Play: Align Host and Play timers

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#1084]

**Comment by drewjhart** [comment]
This issue is based around a situation that has been observed in the classroom. Apparently, it's quite common for students to change tabs and navigate in other browsers while they are playing a game. 

This is problematic for us, as we are running a timer on the page using `requestAnimationFrame`. For performance reasons, a browser will often scale down the available content running on unfocused tabs and `requestAnimationFrame` is one such process. 

This means that if a teacher starts a game, a student can view a question, tab out of the game and their timer will not continue to run. They can then take as long as they want, and when they tab in, they will have their original time remaining.

To solve this, we will need to synch up the time between the `host_v2` and the `play` apps. 

I spoke with Mani about how to do this and he provided a few answers:

1. We could continually provide updates to `play` from `host` on the state of the timer, with an allowable tolerance. For instance, every 3s we could update all instances of `play` by pushing an update to the `GameSession` object. This was an original suggestion from way back and when I roughly implemented it, it just resulted in a ton of networking traffic. I would like to shelve this option and explore other options. 

2. We could establish a server-side clock that runs when a question is started. Players could then query this clock whenever the tab is refocused so there is a single source of truth of all apps. I think this is the best solution but don't know the specifics for implementing the clock on AWS (is it a lambda? is there another service? I'm not sure).

3. We could simply write the current time when the question is first started to `localStorage`. Then when the tab is refocused, get the new current time from the system clock, compare the two, and adjust the timer accordingly. There may be some slippage between `play` and `host` (as we aren't maintaining a single source of truth) but it will get us most of the way there. 


Given that we are on an accelerated timeline for `host_v2` and that this is a high priority item, I would like to implement on #3 initially. Then, once we have it up and running, we can do some research on #2 to see if it's worth migrating over to a solution like that via a proof of concept.
