### ISSUE TITLE
[Host_v2] - E1 Enhancement Changes

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#1134]
This is an issue to track Design changes to `host_v2` as a result of Enhancement 1. Changes listed below have corresponding changes in the Figma files.

**Comment by OliviaKnestaut** [comment]
_While most of these changes were created in the Short Answer Flow, Many of them are applicable to multiple choice as well. After I handle the lobby designs I will create these screens for the Multiple Choice Flow._

### General/Overarching Changes

| Change Notes     | Image |
| ----------- | ----------- |
| "Featured Mistakes" renamed to "Common Mistakes" across all mockups | <img src="https://github.com/user-attachments/assets/e9dfe514-474e-42db-ac5f-0a9bb80a1361" width="300px"> |
| "Responses" renamed to "Phase 1 Responses" across all mockups. This card of responses also appears in phase 2, and the name "responses" could be confusing, causing users to believe they are new responses, and not answers from the previous phase.  | <img src="https://github.com/user-attachments/assets/0b55bc37-c39f-445d-ba33-5287031b885f" width="300px">  |
| The letters A, B, and C in multiple choice and short answer phase 2 should change from the dark grey/black to the purple used for the correct answer step numbers. This makes these letters stand out more, especially in the Phase 2 review section. | <img src="https://github.com/user-attachments/assets/cccc836d-9edf-4961-a32c-fdbd66b99738" width="300px"> <img src="https://github.com/user-attachments/assets/d57f2e35-8fd5-4a6e-81a6-d714fd097d50" width="300px"> |
| Incorrect Answer boxes should all be independently labeled with "Incorrect Answer" consistently across both play and host | <img src="https://github.com/user-attachments/assets/f0a5e9d4-f0c9-4b9c-9801-d9697e4161e1" width="300px"> |

### Short Answer _Phase 1 Answering_

| Change Notes     | Image |
| ----------- | ----------- |
| "Common Mistakes" cannot be selected during this time. This decision is based on UX team's discussion and conversations with Math Corps Philly Teachers. Instead, there is a [live updating preview of common mistakes](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15173-144544&t=FN93sCyomj0fd7qg-4) | <img src="https://github.com/user-attachments/assets/4e0813b7-e5a7-4beb-af7f-b569a8c8191a" width="500px"> |
| Incorrect answers should not be listed in Host during Phase 1, because they have not been entered by students yet. The right-most column should be the [question and the correct answer only](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15173-144544&t=FN93sCyomj0fd7qg-4)   | <img src="https://github.com/user-attachments/assets/d478a117-6205-4fc6-a95a-106203f1a7fe" width="500px">  |


### Short Answer _Phase 1 Review_

| Change Notes     | Image |
| ---------- | ----------- |
| The question card column has been moved to become the first column. This differentiates [this host screen](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=20830-87038&t=FN93sCyomj0fd7qg-4) from the previous and puts the teachers focus on a screen similar to what the students are seeing during review time (especially if they are on a mobile device). | <img src="https://github.com/user-attachments/assets/72a91a86-759d-4b4b-9a03-79b3ea3ac280" width="800px"> |
| Phase 1 scoring is now integrated into [the review screen on the play side](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15530-182647&t=FN93sCyomj0fd7qg-4) | <img src="https://github.com/user-attachments/assets/3ae81cb0-9af7-4012-9927-e6e130d4aaa2" width="800px">  |

### Short Answer _Phase 2 Review_

| Change Notes     | Image |
| ---------- | ----------- |
| The question card column has been moved to become the first column. This differentiates [this host screen](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=20830-110430&t=FN93sCyomj0fd7qg-4) from the previous and puts the teachers focus on a screen similar to what the students are seeing during review time (especially if they are on a mobile device). | <img src="https://github.com/user-attachments/assets/1eab582f-bd0b-4352-ab95-11959176ebe0" width="800px"> |
| The column with answers and confidence from Phase 1 has been pushed to the third column because at this time teachers want to focus on the new incoming Phase 2 responses and player thinking. | <img src="https://github.com/user-attachments/assets/a0cebbd9-5ce0-4bb3-8492-ea009f562c3f" width="800px"> |
| In the [question card column for Phase 2](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=20833-127540&t=FN93sCyomj0fd7qg-4), the incorrect answers are placed above the correct answer, as they are the focus of the Phase 2 review. It is also important that the host sees the percentages here to help them facilitate the lesson/discussion. The order of these incorrect answers on host should reflect the order of the incorrect answers that appear to students. | <img src="https://github.com/user-attachments/assets/a6c31fa5-627a-4024-b63e-4c7a44edc013" width="800px"> | 
| This design is the [UX Team's preferred Phase 2 Review design](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15588-74889&t=FN93sCyomj0fd7qg-4). The percentages beneath the incorrect answers can help students connect that number to the points they receive, while the graph brings the numbers together. The incorrect answers + explanations are on the left so students will see and focus on them first, especially if they are on a phone | <img src="https://github.com/user-attachments/assets/d941b41e-f917-4488-856f-eb00b68c1c99" width="800px">  |

**Comment by drewjhart** [comment]
Such a sick write up, @OliviaKnestaut! 🚀 Let's review this during our design review meeting tomorrow.

**Comment by kellycouvrette** [comment]
Hey @OliviaKnestaut , Drew and I just went over these changes and came up with some questions.
1. How does that new points animation work on the play facing side? For both phase 1 and phase 2.
2. Should the size of the header on the play facing side match that of the host facing side? Currently the play header spans the entire width of the screen and the host side does not.
