### ISSUE TITLE
Host v2.1 & Play v2.1 updates

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#1137]

**Comment by OliviaKnestaut** [comment]
### General/Overarching Changes

| Change Notes     | Image |
| ----------- | ----------- |
| "Responses" renamed to "Phase 1 Responses" across all Phase 2 screens. This card of responses also appears in phase 2, and the name "responses" could be confusing, causing users to believe they are new responses, and not answers from the previous phase.  | <img src="https://github.com/user-attachments/assets/0b55bc37-c39f-445d-ba33-5287031b885f" width="300px">  |
| The letters A, B, C, and D in multiple choice and short answer phase 2 should change from the dark grey/black to the purple used for the correct answer step numbers. This makes these letters stand out more, especially in the Phase 2 review section. | <img src="https://github.com/user-attachments/assets/cccc836d-9edf-4961-a32c-fdbd66b99738" width="300px"> <img src="https://github.com/user-attachments/assets/d57f2e35-8fd5-4a6e-81a6-d714fd097d50" width="300px"> |
| Incorrect Answer boxes should all be independently labeled with "Incorrect Answer" consistently across both play and host | <img src="https://github.com/user-attachments/assets/f0a5e9d4-f0c9-4b9c-9801-d9697e4161e1" width="300px"> |

### "Featured Mistakes" Changes

| Change Notes     | Image |
| ----------- | ----------- |
| "Featured Mistakes" renamed to "Common Mistakes" across all mockups | <img src="https://github.com/user-attachments/assets/e9dfe514-474e-42db-ac5f-0a9bb80a1361" width="300px"> |
| In short answer mode "Common Mistakes" will now be selected during the Phase 1 Reviewing stage, not the Phase 1 Answering stage. This decision is based on UX team's discussion and conversations with Math Corps Philly Teachers. Instead, there is a [live updating preview of common mistakes](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15173-144544&t=FN93sCyomj0fd7qg-4) | <img src="https://github.com/user-attachments/assets/5b048251-c2e7-45b2-8c0a-0eaab90f0b2b" width="500px"> |

### Short Answer _Phase 1 Answering_

| Change Notes     | Image |
| ----------- | ----------- |
| Incorrect answers should not be listed in Host during Phase 1, because they have not been entered by students yet. The right-most column should be the [question and the correct answer only](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15173-144544&t=FN93sCyomj0fd7qg-4)   | <img src="https://github.com/user-attachments/assets/d478a117-6205-4fc6-a95a-106203f1a7fe" width="500px">  |
| The column with answers and confidence from Phase 1 has been pushed to the third column because at this time teachers want to focus on the new incoming Phase 2 responses and player thinking. | <img src="https://github.com/user-attachments/assets/a0cebbd9-5ce0-4bb3-8492-ea009f562c3f" width="800px"> |
| In the [question card column for Phase 2](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=20833-127540&t=FN93sCyomj0fd7qg-4), the incorrect answers are placed above the correct answer, as they are the focus of the Phase 2 review. It is also important that the host sees the percentages here to help them facilitate the lesson/discussion. The order of these incorrect answers on host should reflect the order of the incorrect answers that appear to students. | <img src="https://github.com/user-attachments/assets/a6c31fa5-627a-4024-b63e-4c7a44edc013" width="800px"> | 
| This design is the [UX Team's preferred Phase 2 Review design](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15588-74889&t=FN93sCyomj0fd7qg-4). The percentages beneath the incorrect answers can help students connect that number to the points they receive, while the graph brings the numbers together. The incorrect answers + explanations are on the left so students will see and focus on them first, especially if they are on a phone | <img src="https://github.com/user-attachments/assets/d941b41e-f917-4488-856f-eb00b68c1c99" width="800px">  |
| Phase 2 scoring is now integrated into [the review screen on the play side](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15530-182647&t=FN93sCyomj0fd7qg-4) so there is no longer a separate scoring phase | <img src="https://github.com/user-attachments/assets/9558956e-cdaa-4109-8917-810a6137bf0e" width="800px"> |

**Comment by drewjhart** [comment]
Outstanding dev issues:
1. Short Answer Response - showing choices not short answer responses for question/answer cards.

**Comment by battlekat88** [comment]
After consideration, We've decided to prioritize #9,#8, and then #5 for V2.1. If #12 is just a txt change, then let'sinclude it in 2.1, otherwise we should include it in v2.2

**Comment by drewjhart** [comment]
I will do V1 + all Small items

**Comment by OliviaKnestaut** [comment]
Mockups for Item 10 and 11 have been modified and finished up for whenever they are needed
![image](https://github.com/user-attachments/assets/499e4f41-42c3-40e6-95e7-f14becdcc9be)

**Comment by drewjhart** [comment]
## Additional Enhancements as of 12/09/2024: 

| Facing  | Change Notes     | Short Answer | Multiple Choice | Dev Effort Estimate |
| ------ | ----------- | ----------- | ----------- | ------------- |
| 1. Host | On the “Prepare the Game” screen, display the total number of students who have joined. Use text counter from Splash Screen  | N/A  | N/A | S | 
| 2. Host | Play E4: Make full-body monster more prominent during PC joining | <img src="https://github.com/user-attachments/assets/673cbcdd-20ac-4d01-8461-7efe11fa6318" width="300px">  | Same implementation as short answer screen | S | 
| 3. Play | Play E7: Make onboarding flow swipe and indicators more accessible | <img src="https://github.com/user-attachments/assets/3403df4b-7ca2-4ff2-8c86-5943d3f58794" width="300px">  | Same implementation as short answer screen | M | 

**Note: Central E1:  Ability to control bold text in question editing to better break up question and explanation content will be held on until mock ups are provided**

**Comment by sincwu** [comment]
Hi All, Just for clarity:
- On 8/16, Zach (aka battlekat88) previously sent out a summary of the team's priorities
- Earlier today (9/12), Olivia made some updates to that 8/16 comment, and I updated it further
- Am thinking that it'd be clearer to just send a recap in a new comment at the bottom of this thread

Below is an updated summary, based on the latest list of enhancements and work effort estimates (thanks, Drew, for the quick turnaround!)
For v2.1 (previously named V1 in this thread): All Small items + Item 5, 8, 9 12, & 14
For v2.2 (previously named V2 in this thread): Items 10 & 11

**Comment by drewjhart** [comment]
(original scope didn't include 13, 14, 15). These will be added to enhancement v2.1 moving forward

**Comment by sincwu** [comment]
Hi All, 
- Chatted with Drew and Rod (just added) yesterday about this Github issue, which tracks items for Host/Play 2.1
- As Drew has noted above: mockups for enhancement Central E1 remain pending, and let's incorporate that into planning for Central 2.0/2.1
- @OliviaKnestaut: When you're back on Monday, please remember to add the P4 text change for the Game Code error message (a. more concise copy, b. parsing)

**Comment by OliviaKnestaut** [comment]
Hi All,
I just added rows 16 and 17 to the table above. 16 deals with adding intentional late joining as a feature, and 17 is just a text change for the play game code error message. Please add dev estimates when you get a chance.

**Comment by drewjhart** [comment]
@OliviaKnestaut let's talk about this at today's meeting
