### ISSUE TITLE
[Central_v2] - Bug Report - # line 6 Desktop

### ISSUE THREAD

**Issue by chelcha** [rightoneducation/righton-app#1373]
**Describe the bug**
Highlight on click: Question card is already highlighted

**To Reproduce**
1. Right you open the create question page the card is already highlighted.

**Expected behavior**
Highlight to appear on click

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Chrome & Safari

**Additional context**

**Comment by drewjhart** [comment]
Hey @chelcha, do you see this condition in the Figma anywhere? I'm not super sure what the expected behaviour here is but in this Figma design:

https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=21108-644264&t=BtUNR4OMBcynJBlm-4

And in the Loom video:
https://www.loom.com/share/2ebbed30376d4c1db595a0399f98bd82?sid=49261443-ba6c-4307-a4a2-a4e2e29f6ec2

The first question card is already highlighted. Is the design intent different?

**Comment by rod-hinn** [comment]
Exec decision: question card should already be highlighted. No Bug there. Closing.
