### ISSUE TITLE
Update Question and Game cards according to the new design

### ISSUE THREAD

**Issue by ankittrehan2000** [rightoneducation/righton-app#153]
Update the existing card design and replace it with the following implementation
The following image may be replaced with another design so refer to the figma <a href="https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-MVP-Screens?node-id=3259%3A105632">here</a>

<img width="977" alt="Screen Shot 2021-12-16 at 1 29 05 PM" src="https://user-images.githubusercontent.com/47463734/146428215-c5a2a933-5661-47eb-860f-d7e7be502dc5.png">
">

**Comment by zach2025** [comment]
Because of changes made to the Figma design of the Dashboard, the MVP will only have the Games Dashboard (as the Questions Dashboard has been removed for now). The Games Dashboard has already been updated to the current Figma design and merged into sprint1-branch, therefore this issue is currently done.
