### ISSUE TITLE
Update Question Detail screen

### ISSUE THREAD

**Issue by ankittrehan2000** [rightoneducation/righton-app#155]
<img width="847" alt="Screen Shot 2021-12-16 at 1 36 55 PM" src="https://user-images.githubusercontent.com/47463734/146429207-056bcc3f-a587-4331-8758-5edfe02cd15d.png">

**Comment by zach2025** [comment]
A Pull Request for these changes was not created as they were accidentally pushed directly from my local branch to the sprint1-branch. Because there is no PR to put the information about these changes, the documentation is here instead.

_**Images of what it is supposed to look like are at the bottom**_

**Changes:**
- Creation of Question Detail page according to the Figma design, including Routing to it (Current Issue)
- Default font is now ‘Poppins’ as used in the Figma for all RightOn Central screens
- Default image for all images without a URL is updated to the new placeholder image
#177
- Removed the duplicate Game Dashboard (Undocumented Issue)
- Merged Resolver and Schema updates Ankit made to the dev branch into this branch
#164

**Work In Progress:**
- Wrong Answers - Currently there is no wrong answers or wrong answer explanation data in the database, so once I can put in some test data, I can make it work dynamically for each Question
- Dropdown - Currently the dropdown functionality is all linked to the same function. Separating the correct and wrong answers dropdown functionality is not hard however, getting it for each individual wrong answer may not be possible with the current way they are implemented (need to do more research)
- Correct Answer Flag - The checkmark next to the correct answer card is not there. I have not tried implementing it yet but that feature may cause a few issues and need to be either redesigned or left out (will know when I start trying to code it)

**Known Issues/Bugs:**
- Certain images make answer list stretched because of their length/height (Solution: Crop or Squish image to reasonable size)
- Triple Dots for Question cards on Game Launch brings you to Question detail screen instead of displaying the pop-up (Solution: Rework clicking on the card to exclude the triple dots or be on a double click, or Get rid of triple dots as that feature may not make sense on that screen)
- Correct Answer Explanation is not formatted correctly as it displays the content of the entire instructions attribute (Solution: Need to extract the steps from the attribute)
- Game Maker text in Navigation is cut off due to font change (Solution: Fix overflow property)
<img width="1674" alt="Screen Shot 2022-01-21 at 4 00 14 PM" src="https://user-images.githubusercontent.com/90917774/150602079-b5c2448d-ef22-474b-8c52-d16c0ea72da7.png">
<img width="1674" alt="Screen Shot 2022-01-21 at 4 01 24 PM" src="https://user-images.githubusercontent.com/90917774/150602081-ee1d6d38-eec7-4325-8094-9305e144ac28.png">
<img width="1674" alt="Screen Shot 2022-01-21 at 4 01 31 PM" src="https://user-images.githubusercontent.com/90917774/150602083-aafe0f30-9821-40f6-93d5-b5b5eab788ec.png">
<img width="1674" alt="Screen Shot 2022-01-21 at 4 24 39 PM" src="https://user-images.githubusercontent.com/90917774/150602101-5dc25e01-e791-46cc-ac31-e6e50dc6521a.png">
<img width="1674" alt="Screen Shot 2022-01-21 at 4 25 31 PM" src="https://user-images.githubusercontent.com/90917774/150602168-9e0a8c78-9cd3-408d-a9dd-c335d75854ff.png">
