### ISSUE TITLE
"Don't Get Tricked!" screens are displaying incorrect instructions

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#31]
### Observed
"Don't Get Tricked!" screen shows "Pick the most popular trick answer for a bonus (+25)"
Screenshot on iPhone X:
![IMG_653DD15F1E2B-1](https://user-images.githubusercontent.com/1576365/87448977-241f1200-c62f-11ea-8834-d1e4ba3693ed.jpeg)

### Expected
"Don't Get Tricked!" screen shows "Pick the correct answer  to get for your team (+25)"
Screenshot from Figma [(link)](https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-MVP-Screens?node-id=1044%3A56210):
![Don't Get Tricked!](https://user-images.githubusercontent.com/1576365/87448633-ac50e780-c62e-11ea-93b6-3a5ccc0b3092.png)

**Comment by amarax** [comment]
I think the build is #29

**Comment by maniramezan** [comment]
Actually, related to https://github.com/rightoneducation/righton-app/pull/36 changes

**Comment by sincwu** [comment]
Yong Lin and I verified that the correct message now appears -- great! A minor item: at least on an Android device (Galaxy S7), the text and button appear slightly misaligned (e.g., compare the attached screenshot with the Figma). If this can be fixed with a relatively quick adjustment, great; if not (and especially if this might be a display hiccup unique to older devices), no worries -- we can defer to later.

![image](https://user-images.githubusercontent.com/8507656/88703606-c1fbed80-d0c1-11ea-9f10-5c092f48922a.png)
