### ISSUE TITLE
Not able to select answers in Trick Answer selection screen

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#44]
When viewing this screen, pressing on the grey dots doesn't select the answer.

Tested on iOS 13.7 iPhone X

![IMG_CCF7CD4524BB-1](https://user-images.githubusercontent.com/1576365/94571928-09aa1b80-02a3-11eb-992f-86ed13f14024.jpeg)

**Comment by amarax** [comment]
The correct answer was not yet entered in this case.

**Comment by maniramezan** [comment]
@amarax Yes, it was my impression that it is the case, if not, let me know, I can change the logic and fix it without any new binary releases.

**Comment by sincwu** [comment]
+1 to the suggestion from today's meeting to focus on the single-device scenario and update screens/details to reflect that. In this scenario, because there's only one device, that device is able to both 1) enter trick answers and 2) serve as a Facilitator who chooses the trick answers that are submitted (the ones that are randomly mixed in with the correct answer and shown to the rest of the class).

As shown in the Facilitator flow in Figma, please note that the Facilitator is able to select/unselect answers as soon as even 1 trick answer has been entered (this can happen before the correct answer has been guessed/revealed). This ability to be able to select/unselect answers as soon as even 1 trick answer has been entered applies to both the single- and multi-device scenarios. Great UX & dev collaboration -- thanks to both of you, Mani & Yong Lin!

**Comment by maniramezan** [comment]
Implemented and pushed to appcenter as part of https://github.com/rightoneducation/righton-app/pull/39. This should be fixed in the latest app version and js bundle
