### ISSUE TITLE
[Central] Provide different functionality based on regular vs admin users

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#469]
### Issue:
The NBC crew mentioned that when segments air, there can be significant spikes in app traffic. Gearing up for a potential wave of interest in late-January (when our segment is currently slated to be aired), it'd be helpful to limit access to Central such that regular users: 1) have read-only access to games/questions (i.e., they cannot create, edit, or delete games/questions), and 2) can launch games. Only internal admins with a password would have full access to create, edit, and delete games/questions. 

### Resolution:

TBD. Initial ideas include:
- Move central.rightoneducation.com to admin.rightoneducation.com (or something along those lines) and place a simple username/password screen in front of it [please note: we'd ideally want to maintain one web app (not 2 versions), providing full access only to admins]
- Update central.rightoneducation.com to be read-only (i.e., users can launch pre-existing games, but cannot create, edit, or delete games/questions)
- The following draft Figma screens show functionality that might be disabled/removed for regular users / non-admins:
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12122%3A380137&t=2E8G69FwtTCkxFSM-4

In the future, we will want to:
- Implement a Google OAuth / Cognito-based login system (Based on our last dev team meeting, it sounds like the code for the Cognito-based login system may not have been fully implemented and has been commented out. While a login system that includes email verification might be preferred in the longer term, in the short term, we'll want to make it as easy as possible for early beta users to get started, minimizing or altogether removing the friction of creating an account.)
- Consider a Google OAuth solution or the like (where people can just sign in with a pre-existing account vs. having to create a new one requiring email / phone verification) before implementing a Cognito-based system (or similar)
- Create different user roles with different permissions

**Comment by zach2025** [comment]
Writing this here because I currently cannot get my dev environment working

There are two options we can do:
1. Have a singular production build and have a login page for `admin`, but `central` will bypass it however this disables any editorial features (aka login enables all these features like creating a game, editing questions, etc.)
Pros:
- Allows for one continuous build to maintain and push into production when changes are made, therefore eliminating the need to constantly update two separate versions of the same product or even make sure both function regardless of any changes to one of them if the stripped version in `central` is only changed after significant changes to the all features version in `admin`
Cons:
- This means that we'll need to build some sort of authorization feature or rework/reuse Ankit's authorization code, and check for that in the code and add properties to the specific components that need to be disabled (and creating this authorization and implementing this check and enabling/disabling for the components may be too time-consuming)

2. Have production builds for admin and central, and central would be a stripped version of admin completely removing the ability to even access or display these editorial features in any capacity
Pros:
- Easy to initially implement if we want a working version extremely quickly for kids/teachers to utilize
Cons:
- Since this means we are technically maintaining two different versions of RightOn Central, new features added to the all features version (`admin`) would need to be either implemented into the stripped version (`central`) or `admin` needs to be stripped of the editorial features and then pushed into `central` production
