### ISSUE TITLE
[Central] Image sizes on explore page are hardcoded

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#470]
### Issue:
The image sizes on the game cards on the explore page are hardcoded, leading to some janky behaviour when the window is resized.

### Resolution:
Refactor code for responsiveness. 

_Related:_ https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11960%3A377323&t=NdCMgxvs6kLXWeHk-0

**Comment by zach2025** [comment]
Writing this here because I currently cannot get my dev environment working

Changing certain properties like `width` and `height` to be based on `percentage` or `viewport-height` or `viewport-width` would ensure the image component of the Game card would be totally responsive. To also fill in the square preview of the image when it is not an exact match in size (i.e. the image is taller and narrower than the preview box, leading to an either shrunken image that is narrower than others or an extremely stretched image in both width and height) there could be a property added to zoom into the picture and crop it to size rather than having these weird properties.
