### ISSUE TITLE
[Central] Search bar overlaps on medium screens

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#471]
### Issue:
Search bar overlaps with Game Creation on Medium sized devices:

### Resolution:
Provide more granularity in formatting between sm md large devices

Small (No change required):
![Image](https://user-images.githubusercontent.com/79417944/208318909-4a078ab1-975d-4385-8532-baf06591a813.png)

Medium (Change required):
![Image](https://user-images.githubusercontent.com/79417944/208318877-de06edc9-acd0-4654-9233-89b51d00fc8c.png)

Large (No change required):

![Image](https://user-images.githubusercontent.com/79417944/208318944-363a0e4f-0720-49b5-ac69-f8553fe12069.png)

**Comment by zach2025** [comment]
Putting this in a comment because I can't get `central` up and running but it seems like the resizing of the elements in the toolbar at the top is based on a variable called `isResolutionMobile` which determines its state using the `useMediaQuery` function with `"(max-width: 600px)"` as input. To account for medium sizes it should be as simple as updating that input to be a larger screen width size, so something like `"(max-width: 780px)"` might work for what we need
