### ISSUE TITLE
[Central] Game maker UI not responsive to small screens

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#472]
### Issue:
The game maker pages are not formatting correctly on small devices.

### Resolution:
Rewrite styling to provide responsive formatting for small devices.

### Example:

![Image](https://user-images.githubusercontent.com/79417944/208319316-d87b4a8e-ff24-44fa-a4ca-e369ee7f2012.png)

**Comment by zach2025** [comment]
Writing this here because I currently cannot get my dev environment working

In order to do this properly to account for a responsive design, the breakpoint sizes for each screen size should be different. Currently, each Grid item has its breakpoint as solely the `xs` property, meaning it is a universal breakpoint for all screen sizes. To change this adding in the properties for medium and large screens with different numbers would help solve a majority of the issues. Some padding and width resizing would need to be changed, as well as changing certain properties to be percentage or viewport-height or viewport-width would ensure this reworking of the page would totally responsive.
