### ISSUE TITLE
[Central] Question creation UI not responsive to small screens

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#473]
### Issue:
The UI for the question creation screens is not responsive to small devices.

### Resolution:
Rewrite styling so that small devices format properly.

### Example:

![Image](https://user-images.githubusercontent.com/79417944/208319894-dabdc132-218e-4e83-99de-a30d3a2a0544.png)

**Comment by zach2025** [comment]
Writing this here because I currently cannot get my dev environment working

In order to do this properly to account for a responsive design, the breakpoint sizes for each screen size should be different. Currently, each Grid item has its breakpoint as solely the `xs` property, meaning it is a universal breakpoint for all screen sizes. To change this adding in the properties for medium and large screens with different numbers would help solve a majority of the issues. Some padding and width resizing would need to be changed, as well as changing certain properties to be percentage or viewport-height or viewport-width would ensure this reworking of the page would totally responsive.
