### ISSUE TITLE
Quick mockup for new Phase 1 scoring ideas (ask students about confidence)

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#556]

**Comment by amarax** [comment]
Also to consider how to support students who take a long time to answer

**Comment by sincwu** [comment]
Adding Yong Lin's cool ideas from Slack: **_Ask the students to rate how confident they are of their answer_**
_Building on that idea, we can make this some form of a game that allows them to hedge their bets: if they're highly confident they can go for a high risk option for a big multiplier, but if they aren't so confident they can go for a safer but guaranteed low multiplier._

Additional ideas for consideration from 2/27 UX/Dev Sync:
- Create a scoring (or other) system where students are incentivized to rate their confidence accurately (e.g., avoid a situation where students could simply rate their confidence highly in order to get the largest multiplier / most points)
- Consider a slider/dial vs. discrete choices (e.g., low, medium, high)
- Consider different words/emojis that may be clearer and/or more comfortable to students
- Help teachers identify which students are guessing randomly / have no idea / need the most help
