### ISSUE TITLE
[Play] - Student-Facing Confidence Meter - Design/Dev Coordination

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#728]
**Issue:**
We have finished a draft of the student confidence meter based on [this](https://github.com/rightoneducation/righton-app/issues/705) and would like to request the Design teams review and feedback on this component. Per @amarax's request, we can use this Github issue to track comments/resolution. Yong Lin, I've just added you to this issue so you can add whoever on the Design team needs to see this.

**Previews:**
Alex has put together a series of screenshots [here](https://docs.google.com/document/d/1jmtpX5jbtc-tGawsahoqiZp_iczUxjaqyETtltnGp1M/edit) and you can find the latest Chromatic to see it in action [here](https://64220218d457f84ba4546eb1-fivohldtsh.chromatic.com/). I've posted a link to add yourself to the Chromatic in slack if you have any permission issues. Finally, here's a copy of the video Alex created:

https://github.com/rightoneducation/righton-app/assets/79417944/d1e32a88-bfc2-4747-a9fe-4ba16af4d0da

**Comment by amarax** [comment]
@Alexandra-Kushnirsky thanks for putting together your screenshots! What you've done so far looks good! For now, we'll leave it as is, because there will be a few margin/border changes to optimise the readable area on screen, allowing the scale to still be fully horizontal on the smallest typical mobile device:
![image](https://github.com/rightoneducation/righton-app/assets/1576365/02de6a38-50b1-4ab9-9acc-4a39779962f7)

Another piece of design debt to address is to have different font sizes for different screen widths. This is common for responsive designs to address what you mentioned earlier in your document (small borders and small fonts looks awkward on larger screens).

Specific notes:
- We'll be ignoring the Galaxy Fold as a target device. It's unlikely for our users to be using that specific device in its folded form. Please skip the screenshots for this device in future!

**Comment by amarax** [comment]
One separate item: I'd like to configure some animation for these cards to appear after the response to the earlier question is submitted. This animation should be generic for all cards that appear as a result of user interactions.

1. Animate both `height` and `margin-top` from 0 to its default value, using `animation: 500ms ease-in-out`.
2. Experiment with `opacity` from 0 to 100 using the same animation, and let me know which one looks better.
3. The content of the card should not have additional animation on top of this.
4. For `@media (prefers-reduced-motion: reduce)`, just pop in the card and fade it in using `animation: 300ms ease-in-out`.

**Comment by Alexandra-Kushnirsky** [comment]
I also just had a more general question: is the confidence meter meant to be displayed for phase 2 "choose the trickiest answer" as well or just for phase 1 "choose correct answer"? And if so is the response in relation to how confident the player is of their answer in phase 1 or the most popular wrong answer (i.e. should we be storing the confidence level in phase 2 as its own confidence level separate from phase 1's confidence level if we are in fact displaying the card in phase 2)?

**Comment by amarax** [comment]
Hi @Alexandra-Kushnirsky sorry for the late reply! I think there are a few tweaks for the animation but this should be good for now. Do leave the expanding circle (I'm assuming the expanding black circle is part of the screen capture, while the expanding light blue circle is what you're referring to?) because it's good feedback for a selection.

**Comment by amarax** [comment]
We are not planning to use this in Phase 2, but the component should let it's parent decide what is displayed as the text content.
