### ISSUE TITLE
[Host] - Real-Time Responses Graph Component Design/Dev Coordination

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#753]
## Overview ##
This is a general issue to track coordination and feedback from the Design team on the Real-Time Responses graph on the `host` app. You can find the Figma design for this component here:

https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?type=design&node-id=15172-167577&mode=design&t=FGcyIy2OAO27xWQk-4

And you can find Josephina's description of the component as well as links to videos and a Chromatic link here:
https://righton-education.slack.com/archives/C02D6KZ029L/p1690478112291619

Appreciate the feedback in advance!

**Comment by amarax** [comment]
I'm including the direct Chromatic link for easy access here too https://64220218d457f84ba4546eb1-iewhbvtiho.chromatic.com/?path=/story/responsesgraph--different-answers

**Comment by amarax** [comment]
Here's my feedback for the component! (I'll be using cards as a convenient way to show examples for the graph, but ignore them for now and just focus on the graph component inside.)

Usability:
- If the response can be chosen by students during that phase, a zero should be displayed. This helps the teacher know that it is a possible option but no students have picked it. ![image](https://github.com/rightoneducation/righton-app/assets/1576365/e37e493d-378c-4ebb-ac7b-123d7bedd76f)
- Numbers on the bar should be right-aligned, so that it accommodates single to triple digit numbers properly.
- The hit area for the item should always be the entire width of the chart, so that even small values can easily be selected. Example: ![image](https://github.com/rightoneducation/righton-app/assets/1576365/c067ccee-1f83-4e63-b360-98b0f0f7f824)
- As the bars are interactive elements, they should have appropriate hover states, and the cursor should be a pointer.
   - As a quick implementation for a hover state, just add a 50% transparent white overlay in the background. This should also apply for the selected state. We'll get back to the visual design of this in future, but for now this will suffice.
- The scaling of the graph currently seems to be based on matching an aspect ratio, constrained by width of container. Can this be a fixed height instead with a variable width? Example: ![image](https://github.com/rightoneducation/righton-app/assets/1576365/7e5a5e69-092f-4433-ad9d-d130b2b1e1b1)
   - I'd recommend all sizes to be in em, so that as we develop the responsive guidelines in future and have adjustments for larger/smaller font sizes for different screens, the graph will be sized properly.
- Tooltips for the –/A/B/C/D will be needed:
   - "Players who have not responded" for the – (note that this is the en dash character `–`, not the hyphen `-` character)
   - "This is the correct answer" for the tick

Appearance (lower priority):
- If the bar is shorter than the width of the number, the number should appear to the right of the bar instead. This is not super important as in most cases, even 1 student should have a bar of significant width. 
   - The exception to this is for zero, which is always displayed to the right of the bar, and is not optional.
- If possible, the scale should have a minimum minor axis tick of 5. Even for low numbers, a minor axis tick of 2 is harder to process.
- The borders, spacing and dimensions are all slightly off from the Figma designs.
   - The most glaring issue is the thickness of the bar: ideally it should be 1.5x the font size at least.

Planned enhancements, to factor in when building the component now:
- A label for each bar will be needed in future, and may be a way to display the answer to the question, to be used in conjunction with A/B/C/D ![image](https://github.com/rightoneducation/righton-app/assets/1576365/e6df5023-4489-4a86-a233-d4e61470b2a0)
- The bars may be coloured differently based on their status, to provide a clearer indicator for teachers. For example, the correct answer may be always associated with green. The design for this is still TBC.

**Comment by josephinaim** [comment]
Hi @amarax, thanks for the feedback! I was wondering for the tooltip, what the user interaction would be? So, the selected bar has a hover state of a white highlight and this encompasses the "-" and the tick. Would the hover state mean the tooltip and the white highlight appear? Please let me know.

**Comment by amarax** [comment]
@josephinaim yes for now that should be the case, and I'm assuming that's the default behaviour from MUI. If that's not the case let me know. I'm aware that this may be problematic on mobile, and at this point I'll need to test it first to understand what's a better direction to go ahead with.
